---
name: Docker Socket Proxy
version: dev
slug: docket-socket-prxy
description: It is a self-hosted monitoring tool like "Uptime Robot"
url: https://github.com/hassio-addons/docker-socket-proxy
codenotary: codenotary@frenck.dev
webui: http://[HOST]:[PORT:3001]
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ports:
  3001/tcp: 3001
ports_description:
  3001/tcp: Web interface
